// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNRxIBYRsulRv12FJpdl3bvMtLfcJAY0',
    appId: '1:297075599265:web:e480c2f30a5566fbe8cde0',
    messagingSenderId: '297075599265',
    projectId: 'safedriveuserauth-1e624',
    authDomain: 'safedriveuserauth-1e624.firebaseapp.com',
    storageBucket: 'safedriveuserauth-1e624.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSw0ek3qR-5yWKFY3FhVxT1TNWb82gZb4',
    appId: '1:297075599265:android:61dccbcf3d07be52e8cde0',
    messagingSenderId: '297075599265',
    projectId: 'safedriveuserauth-1e624',
    storageBucket: 'safedriveuserauth-1e624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa32r7xHszZ92K6YZ7epZf0HXrEqy3wwA',
    appId: '1:297075599265:ios:d3ce79bba95a96c3e8cde0',
    messagingSenderId: '297075599265',
    projectId: 'safedriveuserauth-1e624',
    storageBucket: 'safedriveuserauth-1e624.appspot.com',
    iosBundleId: 'com.example.safedrivealan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa32r7xHszZ92K6YZ7epZf0HXrEqy3wwA',
    appId: '1:297075599265:ios:d54046845f109ad8e8cde0',
    messagingSenderId: '297075599265',
    projectId: 'safedriveuserauth-1e624',
    storageBucket: 'safedriveuserauth-1e624.appspot.com',
    iosBundleId: 'com.example.safedrivealan.RunnerTests',
  );
}
